### ISSUE TITLE
Filter with paginator

### ISSUE THREAD

**Issue by Cannonb4ll** [Tucker-Eric/EloquentFilter#1]
Really, really good package, using it in a big project now and i'm loving it.

One thing I would like to notice, that you might want to add to the documentation, is the paginator.

When you render the default laravel paginator, the GET values in the URL will drop when you switch to another page, I have resolved this by rendering the paginator this way:

    {!! $pages->appends(Input::except('page'))->render() !!}

This would generate URL for example:

    app.com/pages?title=PageTitle&page=3

(Otherwise, the paginator would override the filter options and clear it from the url so you would loose your filter)

**Comment by thijsdemaa** [comment]
+!

**Comment by Tucker-Eric** [comment]
Great suggestion!

I liked your idea so I added 2 new methods available on the models that use the `EloquentFilter\Filterable` trait.

You can now use `$query->paginateFilter()` or `$query->paginateSimpleFilter()` in place of the `$query->paginate()` method to keep your query string in tact when you call `{!! $pages->render() !!}`

**Comment by thijsdemaa** [comment]
Amazing, thanks!
