### ISSUE TITLE
Eloquent Filter overiding global scopes

### ISSUE THREAD

**Issue by Drewdan** [Tucker-Eric/EloquentFilter#115]
Looking to get some clarification.

I have added some global scopes to a model, which uses the Eloquent Filter. It appears when using the filter, these global scopes are not applied. Is this expected behaviour?

Thanks

**Comment by Tucker-Eric** [comment]
That's not the expected behavior. Global scopes should be in tact. Depending on how the global scopes are being applied and how the filter is being called could be the cause of the global scopes being overridden.

**Comment by Drewdan** [comment]
My apologies, after further digging, I realsied that the scope was being applied, but the builder not being updated properly as it could not access the Auth facade in the constructor which I believe is an issue specific to my project.

Thank you for your time!

**Comment by Tucker-Eric** [comment]
No worries! Glad you got it figure out! 👍
