### ISSUE TITLE
require for  json handle filtering 

### ISSUE THREAD

**Issue by harrisdt15f** [Tucker-Eric/EloquentFilter#116]
Question: How to Naming method names for json fields 
here is field name inputs with json type in table 
![image](https://user-images.githubusercontent.com/27404296/79938381-08242e00-848f-11ea-9a48-ced310debb5f.png)

I don't know  by writing this way is ok or not.

```php
public function jsonInput(int $inputId)
{
    return $this->where('inputs->id', $inputId);
}
```
please also support for json field filtering method if possible.

**Comment by Tucker-Eric** [comment]
Depending on how complex that json input can get you can filter raw json a couple of different ways.

Let's say you have filter input of:
```php
MyModel::filter(['json_input' => '{"id":1,"status":0}'])->get();
```

You can create just one method that will handle this json:
```php
public function jsonInput(string $json)
{
    $data = \json_decode($json, true);

    return $this->where('inputs->id', $data['id'])->where('inputs->status', $data['status']);
}
```

Or if you want to take advantage of individual methods you can merge the input in a `setup` method that gets called before any filtering happens to make the input available to all filter methods:

```php
// The filter looks for a method called `setup` so defining one ensures this is called before any filtering happens
public function setup()
{
    if($json = $this-input('json_input')) {
        $this->push(\json_decode($json, true));
    }
}

public function id($id)
{
    return $this->where('inputs->id', $id);
}

public function status($status)
{
    return $this->where('inputs->status', $status);
}
```

Or if you wanted to prefix your json methods you could do that in your setup method too:
```php
// The filter looks for a method called `setup` so defining one ensures this is called before any filtering happens
public function setup()
{
    if($json = $this-input('json_input')) {
        foreach(\json_decode($json, true) as $key => $val) {
            // Because we are prefixing the keys here, when they are filtered they will look for the appropriate methods they correlate to.
            $this->push('json_' . $key, $val);
        }
    }
}

public function jsonId($id)
{
    return $this->where('inputs->id', $id);
}

public function jsonStatus($status)
{
    return $this->where('inputs->status', $status);
}
```

I hope this helps! Let me know if I can clarify anything!

Cheers!

**Comment by harrisdt15f** [comment]
I like this way, thank you very much for sharing me knowledge.
![image](https://user-images.githubusercontent.com/27404296/80183502-832a4780-863b-11ea-860a-d951d5b00e66.png)
