### ISSUE TITLE
Applying filter to a relationship collection

### ISSUE THREAD

**Issue by devchalkie** [Tucker-Eric/EloquentFilter#117]
Hi,
I have User model which has relationship say books(), i want to do something like $user->books->filter($request->all()) so that user can only filter through his books.

Any suggestion please.

Thanks,
Hussain

**Comment by Tucker-Eric** [comment]
Yup, you can do that if you switch to calling `books` as a method so you still have access to the related query before it's executed.

This should do the trick:
```php
$user->books()->filter($request->all())->get();
```

**Comment by devchalkie** [comment]
Thank you a lot, that makes it a lot easier :) awesome work. 👍

**Comment by bitdev1999** [comment]
Don't work for me

**Comment by bitdev1999** [comment]
$searches = $user->searches()->filter($request->all())->get();

Call to undefined method Illuminate\Database\Eloquent\Relations\HasMany::filter()

**Comment by benrolfe** [comment]
@bitdev1999 I have the same issue. Any suggestions @Tucker-Eric?

**Comment by Tucker-Eric** [comment]
In that case he relation needs to use the `Filterable` trait.  So the model that `searches` returns in the relationship needs to implement that `Filterable` trait.
