### ISSUE TITLE
How to use group by or  multiple group by criterias

### ISSUE THREAD

**Issue by harrisdt15f** [Tucker-Eric/EloquentFilter#122]
![image](https://user-images.githubusercontent.com/27404296/85517676-0fec8400-b632-11ea-942b-1198c448f92f.png)
for example I need to select the result containing sum of win_money with 
game sign by created_at (daily/monthly) for day report or monltly report of each game under each vendor
game_vendor_sign by created_at(daily/monthly) for day report or monltly report of each vendor
all game result by created_at(daily/monthly) for day report or monltly report of all individual game
how should I use group by or something tricks  please guide me.

**Comment by Tucker-Eric** [comment]
I don't think I understand the question. How are you currently doing this and what is the query you are trying to create?
