### ISSUE TITLE
Filter on append attributes

### ISSUE THREAD

**Issue by Rowmain** [Tucker-Eric/EloquentFilter#148]
It should be great to be able to filter on append attributes.
Despite of using a part of EloquentFilter and use collection method to end the job

Suggestion : 
- Using collection filter / reject

![image](https://user-images.githubusercontent.com/9927586/96878824-5345ea80-148c-11eb-990c-f7180a7229dd.png)
_In this case I would like to get all admin users_

**Comment by Tucker-Eric** [comment]
Thanks so much for the suggestion! However, I don't think this is something we'd want to introduce to this package but may be a great idea for a new one. I would argue that whatever parameters are used to calculate `is_admin` should be constrained before that data is pulled out of the database.
