### ISSUE TITLE
Add orWhereLike

### ISSUE THREAD

**Issue by th3m1n1c0d34** [Tucker-Eric/EloquentFilter#161]
Hey, Simply i had to write:
`      return $this
            ->whereLike('name', $term)
            ->orWhereRaw('LOWER(brand) LIKE ?', ['%' . $term . '%']);`
So it would be helpful to :

`      return $this
            ->whereLike('name', $term)
            ->orWhereLike('brand', $term);`

Thank you for the great package !

**Comment by th3m1n1c0d34** [comment]
[https://github.com/Tucker-Eric/EloquentFilter/issues/78](url)
Found the solution, Hope that it would be added to the documentation.
![image](https://user-images.githubusercontent.com/61377876/120859151-b4ce4b80-c57b-11eb-8660-ba0d1edf2920.png)

**Comment by Tucker-Eric** [comment]
Docs updated https://github.com/Tucker-Eric/EloquentFilter/blob/master/README.md#additional-filter-methods
