### ISSUE TITLE
Access the other request parameters within the filter function?

### ISSUE THREAD

**Issue by yaman3bd** [Tucker-Eric/EloquentFilter#167]
is it possible to access the other request parameters within the filter function?
because I am working on filtering the data in a way like:
```
{
 products: [id, id, id],
 operator: '='
}
```
so in my products function, I want  to be able to use the operator parameter as well
because the operator is changeable it could be` '!=' or '='`

is it possible to access the other request parameters within the products function?

it would be amazing if it could be something like this:
![image](https://user-images.githubusercontent.com/58285821/139942718-d02d7318-a837-4809-8526-8ecdb32aa79c.png)

However, I thought of this idea I do not know if it is right or not

![image](https://user-images.githubusercontent.com/58285821/139942286-504be611-f045-4c33-b3e8-281f51e3a19f.png)

**Comment by Tucker-Eric** [comment]
Yep! You can access it with the [input](https://github.com/Tucker-Eric/EloquentFilter#defining-the-filter-logic) method.

You'd access it in your method via:

```php
$operator = $this->input('operator');
```

**Comment by yaman3bd** [comment]
@Tucker-Eric solved the problem!
thanks a lot
