### ISSUE TITLE
Filter by column and and relation column

### ISSUE THREAD

**Issue by diegonella** [Tucker-Eric/EloquentFilter#170]
Hi guys, great package,

I need help for apply similar to sql query
`SELECT 
p.id 
FROM ecommerce_products AS p
INNER JOIN ecommerce_sku AS s ON p.id = s.product_id
WHERE (p.code LIKE '000614' OR s.code LIKE '000614')`

I have tried in different ways but I did not find the way

**Comment by Tucker-Eric** [comment]
I would just do this in a `where` for the product code on your `EcommerceProduct` model:
```php
public function code($code)
{
    $this->where(function(Builder $query) {
        $query->where('code', '000614')
            // `ecommerceSku` is name of relation from EcommerceProduct -> EcommerceSku
            ->orWhereHas('ecommerceSku', function(Builder $query) {
                $query->where('code', '000614');
            });
    });
}
```
