### ISSUE TITLE
Model scope methods are not working well

### ISSUE THREAD

**Issue by abhimanyu003** [Tucker-Eric/EloquentFilter#18]
I have a strange issue somehow scope methods are giving strange results.

In `User` model there is `scope` function with name `active`

```
    public static function scopeActive()
    {
        return static::whereIsActive(1);
    }
```

So if I do

```
 User::active()->filter($request->all())->latest()->paginate(20);
```

In `Filter` Class

```
    public function q($username)
    {
        return $this->whereUsername($username); // No Additional check is set
    }
```

I also get `User` which are not active.

**But**

If I do
```
User::filter($request->all())->latest()->paginate(20);
```

In filter class

```
    public function q($username)
    {
        return $this->whereIsActive(1)->whereUsername($username); // Additional check is set
    }
```

Results are correct.

**Comment by Tucker-Eric** [comment]
Local scopes shouldn't be declared static on models.  Local scopes inject an instance of the query builder.  If you change your scope function in your `User` model to:

```php
<?php

public function scopeActive($query)
{
    return $query->whereIsActive(1);
}
```

Then this: 

```php
<?php

User::active()->filter($request->all())->latest()->paginate(20);
```

Should work.

It will also allow you to change the order too.
```php
<?php

User::filter($request->all())->active()->latest()->paginate(20);
```
Both of those will produce the same result.

**Comment by Tucker-Eric** [comment]
Let me know if this works and I'll close this issue

**Comment by abhimanyu003** [comment]
@Tucker-Eric thanks for guidance  :) it is working fine
