### ISSUE TITLE
$relations setting to create orWhereHas

### ISSUE THREAD

**Issue by lukevmk** [Tucker-Eric/EloquentFilter#182]
I'm running into an issue where I would like to filter relations via an OR statement in staid of AND. 

e.g. I'm searching models on several columns by a search term. So many ModelFilters implement a `query($term)` method to search that model. Some models required deeper search through relations. We want to give the user as many results as possible for that search term. But the query has a `whereHas` instead of an `orWhereHas` so the result is restricted at the moment.

A possible solution would be to manually write the `orWhereHas` in the top ModelFilter method, but this will end up into duplicate code since this method is also defined in the related ModelFilter. 

Would be awesome if this could be added!

**Comment by Tucker-Eric** [comment]
Hmm, I _think_ I follow what you're saying but not quite sure. Is there a code sample you're able to reference?

**Comment by lukevmk** [comment]
Ofcourse! I hope this example clarifies my case enough.

So, one ModelFilter looks like this currently:

`public function query($term)
    {
        return $this->whereLike('name', $term)
            ->orWhereHas('project', function($query) use ($term) {
                $query->where('name', 'LIKE', '%' . $term . '%')
                    ->orWhere('alias', 'LIKE', '%' . $term . '%');
            });
    }`

But the duplicate code is happening in the `project` ModelFilter:

`public function query($term)
    {
        return $this->whereLike('name', $term)
                ->whereLike('alias', $term, 'or');
    }
`

In this case I cannot use the `$relations` array from the ModelFilter because that wil build an `whereHas`. I am looking for an `orWhereHas`.

**Comment by Tucker-Eric** [comment]
That's an interesting issue. You are able to call other model filters from the parent. Does something like the following work to DRY it up a bit?

```php
public function query($term)  
{
    return $this->whereLike('name', $term). 
        ->orWhereHas('project', function($query) use ($term) {
            $query->filter(['query' => $term]);
        });  
}

```

**Comment by lukevmk** [comment]
wauw, that's pretty smart! Thank you so much for your help!
