### ISSUE TITLE
config directory changed

### ISSUE THREAD

**Issue by robbielove** [Tucker-Eric/EloquentFilter#19]
when I try to create a config file, artisan creates in the app folder, whereas the readme states:

> Where `User` is the Eloquent Model you are creating the filter for.  This will create `app/ModelFilters/UserFilter.php`

I tried a second time to run the command to make sure (using the command in readme - php artisan model:filter User) and got:
> php artisan model:filter User

	/Users/robbielove/dev/xxxxxx/app/UserFilter.php Already Exists!

this is starting to really confuse me about where the file should be located, in saying this - i have tried using it in both app/UserFilter.php and app/ModelFilters/UserFilter.php and still get variations of 
>Class 'App\ModelFilters\UserFilter' not found

the newly generated UserFilter contains:

```<?php namespace UserFilter;

use EloquentFilter\ModelFilter;

class UserFilter extends ModelFilter
{
    /**
    * Related Models that have ModelFilters as well as the method on the ModelFilter
    * As [relatedModel => [input_key1, input_key2]].
    *
    * @var array
    */
    public $relations = [];
}
```
I have tried with and without adding modelFilter() to my user model. nothing I do seems to get it working, I tried with just an orderby() method in-case my code was causing the class not to be created, but still same error.

**Comment by Tucker-Eric** [comment]
There was no default namespace specified in the generate command so the behavior you encountered would have happened if you didn't have a config file at `config/eloquentfilter.php`  This has been updated to default to `App\ModelFilters` namespace without a config file.  You should be good to go.

**Comment by robbielove** [comment]
Thanks for your help, it seems to be working correctly after re-creating the UserFilter again.
