### ISSUE TITLE
Relations with one related method

### ISSUE THREAD

**Issue by DevilSAM** [Tucker-Eric/EloquentFilter#190]
Hi, Eric! 
Your package is awesome! Thank you!

I just want to ask about filtering by relations where related model should use the same method twice.
For example:

```php
class ConstructionFilter extends BaseModelFilter
{
    public $relations = [
        'owner' => [
            'owner.surname' => 'full_name',
            'owner.name'    => 'full_name',
        ]
    ];
}


class OwnerFilter extends BaseModelFilter
{
    public function fullName($value)
    {
        $this->where('full_name', 'ilike', "%$value%");
    }
}
```

So if I try to filter construction by owner's `name` and `surname` it will use only one of these fields and filter it with owner.fullName.

I guess it happens because of under the hood `$relations` combine all the related methods and use one `whereHas` for it.
Of cause I can write two different methods in my `OwnerFilter` with the same logic but I just want to know is there any way to make work the code which uses different keys and same values for one relation?

Thank you.

**Comment by DevilSAM** [comment]
Thanks! 
It works. 
A bit more complicated than adding another method to ownerFilter, but this is exactly what I wanted. Thanks again :) 


P.S. I suppose It must be `input($key)`
```
>  $val = $this->input($val);
```

**Comment by Tucker-Eric** [comment]
@DevilSAM Ahh, yep! Updated reply
