### ISSUE TITLE
Not working with difference connection table 

### ISSUE THREAD

**Issue by abdulbarishaikh** [Tucker-Eric/EloquentFilter#203]
example 
connection 1 table users
connection 2 table user_detail 
can't able to create filter on it

**Comment by Tucker-Eric** [comment]
@abdulbarishaikh are you able to provide more details? I'm not sure this sounds like an EloquentFilter issue as described.

**Comment by abdulbarishaikh** [comment]
Yes, you are right is Eloquent issue not EloquentFilter issue.
Thanks For Your Response
