### ISSUE TITLE
Just a heads up

### ISSUE THREAD

**Issue by designvoid** [Tucker-Eric/EloquentFilter#23]
I just did a test upgrade to L5.4 and your package caused a few errors. I'm not going to be working on the latest version for my current project so don't have time at the mo to fix and submit a PR but figured I'd give you a heads up!

**Comment by Tucker-Eric** [comment]
Thanks for the heads up! I'll test today and see if I can get something
released ASAP.

**Comment by Tucker-Eric** [comment]
Just released the fix in v1.1.0
