### ISSUE TITLE
Dynamic namespace for modular app

### ISSUE THREAD

**Issue by grafikkaos** [Tucker-Eric/EloquentFilter#27]
Is there a way I can set the namespace dynamically for a modular app?

I am currently using the nwidart/laravel-modules package to separate my application.  Some of my modules have a their own separate search facility so the question here is, is there a way I can the namespace for each module dynamically?  

THanks

**Comment by grafikkaos** [comment]
Actually found my own answer to this...

Had to provider my own filter to get this working.

**Comment by Tucker-Eric** [comment]
You can define the filters [per model](https://github.com/Tucker-Eric/EloquentFilter#define-the-default-model-filter).

**Comment by garbinmarcelo** [comment]
Hi @grafikkaos ,

Have you still used this package? 
I also use laravel-modules, I would like to know your experience so far.

I'm starting a new project and I'm implementing the EloquentFilter package.

Thank's
