### ISSUE TITLE
Fuzzy searching

### ISSUE THREAD

**Issue by junelmujar** [Tucker-Eric/EloquentFilter#31]
Hi Eric,

First, just want to thank you for making this wonderful piece of software.

Just want to ask for insights on how to implement fuzzy searching within the defined filters.

Thanks in advance!

Regards,

Junel

**Comment by Tucker-Eric** [comment]
That depends on your personal preference. You can write the logic for each method separately allowing you to option a funny method when present. 

There are some [helper methods](https://github.com/Tucker-Eric/EloquentFilter#additional-filter-methods) included that you can use to do:

```php
public function name($name)
{
    return $this->input('fuzzy') ? $this->fuzzyName($name) : $this->exactName($name);
}

public function fuzzyName($name)
{
    return $this->whereLike('first_name', $name);
}

public function exactName($name)
{
    return $this->where('first_name', $name);
}
```

**Comment by junelmujar** [comment]
I didn't notice the helper methods :) Thanks for that!
