### ISSUE TITLE
Return only certain fields

### ISSUE THREAD

**Issue by lilian21** [Tucker-Eric/EloquentFilter#33]
Hi again,
  Is it possible to return just some selected fields? Like `User::get(['first_name','last_name','email']);` 
There are some cases when I want to hide some fields when searching (like a public search) and I cannot use the protected $hidden attribute to specify those fields because in other situations I need those fields to be shown by default.
Thanks for this awesome package.
Lilian

**Comment by Tucker-Eric** [comment]
Thanks Lilian!
Are you talking about pagination? I'm not sure I understand the question, can you give me an example?

**Comment by lilian21** [comment]
Yes, sorry I didn't mention that. I checked now the paginationFilter method and saw it accepts an $input parameter to specify these fields. Thank you! Keep up the good work!

**Comment by Tucker-Eric** [comment]
Wonderful! Glad to have steered you in the right direction.
