### ISSUE TITLE
Does this support lumen 5.4 ?

### ISSUE THREAD

**Issue by fatkhanfauzi** [Tucker-Eric/EloquentFilter#35]
Does this support lumen 5.4 ?

i get error
```
PHP error:  Call to undefined function EloquentFilter\config_path() in i/vendor/tucker-eric/eloquentfilter/src/ServiceProvider.php on line 17
```

**Comment by Tucker-Eric** [comment]
Commit c6d60c4aa3124ab3fbbd9310ff4eb75274094d35 should fix that and officially support Lumen. Will draft release and update documentation shortly.  You can start using now if update your `composer.json` to require `"tucker-eric/eloquentfilter": "^1.1"` in your composer.json

**Comment by Tucker-Eric** [comment]
V1.2 adds support for Lumen.  Update your `composer.json` to `"tucker-eric/eloquentfilter": "^1.2"` and make sure to register the `EloquentFilter\LumenServiceProvider` instead of the `EloquentFilter\ServiceProvider`

See setup [Lumen Setup](https://github.com/Tucker-Eric/EloquentFilter#lumen)

**Comment by fatkhanfauzi** [comment]
cool.. thanks
