### ISSUE TITLE
Filtering polymorphic relation

### ISSUE THREAD

**Issue by Hytii** [Tucker-Eric/EloquentFilter#38]
Hi there,

First, thanks for this package as it ease the filtering process nicely!

Second, I've got the following case and require assistance :
A Bill or Invoice if you prefer:
```
class Bill extends Model
{
    use Filterable;

    public function modelFilter()
    {
        return $this->provideFilter(BillFilter::class);
    }

    public function billable()
    {
        return $this->morphTo();
    }
}
```

Links to a "billable" something that may have a bill, for the example let's say an order that's been place by a customer:
```
class Order extends Model
{
    use Filterable;

    public function modelFilter()
    {
        return $this->provideFilter(OrderFilter::class);
    }
   
    public function buyer()
    {
        return $this->belongsTo(Customer::class, 'buyer_id');
    }

    public function bill()
    {
        return $this->morphOne(Bill::class, 'billable');
    }
}
```
As you can see the order reference a buyer which I would like to filter on via its name when filtering a bill list.

As the Customer filter already exists I tried with the $relations array as so in BillFilter:
```
    public $relations = [
        'billable' => [ 'customer' ],
    ];
```
and in OrderFilter I've got the following filter method:
```
    public function customer($name)
    {
        return $this->whereLike('name', $name);
    }
```

Thing is it seems that the filterRelations methods goes into an infinite loop in that case. Other test I did was create a "normal" relationship on Bill as so to try if the $relations was setup right:
```
    public function order()
    {
        return $this->belongsTo(Order::class, 'billable_id');
    }
```
Which worked as expected.

Would it be possible to filter with the polymorphic relation or not ? And am I doing it wrong ?

**Comment by Tucker-Eric** [comment]
Ahhh, I see what you're talking about.
Since `billable` is polymorphic the `$relations` array won't access the `OrderFilter` because the nature of the polymorphic relation won't explicitly point to that model which will result in the infinite loop you are talking about. Your work around is the way you should be doing it but you should add a `billable_type` constraint so you don't accidentally get a different model type like:

```
    public function order()
    {
        return $this->where('billable_type', Order::class)->belongsTo(Order::class, 'billable_id');
    }
```
That way it explicitly points to the order model. It's how you would have to do it if you were querying the relationship using `whereHas()` because that's what the filter is using behind the scenes.

**Comment by Hytii** [comment]
Thanks for your reply
Actually I've got the billable_type and these works but will be filter only one type of billable, here order.

Would have a way to set it up so that "customer" would filter the order relation and another type of billable ? 
For example, billable being either an Order or a Ticket .
Both relation would be setup like so:
```
public function order()
{
        return $this->where('billable_type', Order::class)->belongsTo(Order::class, 'billable_id');
}
public function ticket()
{
        return $this->where('billable_type', Ticket::class)->belongsTo(Ticket::class, 'billable_id');
}
```

Thanks for the help

**Comment by Tucker-Eric** [comment]
With those relations set up, change the `$relations` array to:
```
    public $relations = [
        'order' => [ 'customer' ],
    ];
```
And then it will use your `OrderFilter`
