### ISSUE TITLE
Vendor publish is not doing anything

### ISSUE THREAD

**Issue by Cannonb4ll** [Tucker-Eric/EloquentFilter#4]
Since the update, I am not able to publish the configuration file with a new laravel installation.

I have the service provider in my app.php, but its not doing anything.

php artisan vendor:publish --provider="EloquentFilter\ServiceProvider"

**Comment by Tucker-Eric** [comment]
This should be fixed with de957034b2f043c872520d1e4e49531a5a092310

If you still have this issue after update delete `bootstrap/cache/services.php` and run `php artisan vendor:publish --provider="EloquentFilter\ServiceProvider"` again

Let me know if this fixes it and I'll close this issue.
