### ISSUE TITLE
is there a way to specify which query parameters to use when using paginateFilter()

### ISSUE THREAD

**Issue by vesper8** [Tucker-Eric/EloquentFilter#40]
I have a situation where I am passing an array of values to filter() which includes a "sorting" parameter

but it so happens that my "sorting" parameter is not a url query parameter, instead it's part of my route

So my route looks like /submissions/latest?page=2

And I pass 
```
[
    "sorting" => $routeParams["sorting"],
    "page" => $queryParams["page"],
]
```

The filter does its job properly, but then because I'm using paginateFilter

The url produced by the paginator is /submissions/latest?sorting=latest&page=3

How can I tell paginateFilter to not use everything passed to the filter() but only use parameters I whitelist?

**Comment by Tucker-Eric** [comment]
Instead of using the `paginateFilter` method you can do:

```php
YourModel::filter(["sorting" => $queryParams["sorting"], "page" => $queryParams["page"]])
    ->paginate()
    ->appends(["page" => $queryParams["page"]]);
```

Which is basically what is going on in the [`paginateFilter`](https://github.com/Tucker-Eric/EloquentFilter/blob/master/src/Filterable.php#L50) method with all filtered input passed to it.

**Comment by vesper8** [comment]
thanks :)
