### ISSUE TITLE
Using the same $relations values across associated ModelFilters causes PHP Memory Allocation Error

### ISSUE THREAD

**Issue by GarethTIGFreight** [Tucker-Eric/EloquentFilter#41]
If I setup 2 ModelFilters that pass data using the $relations class property I it causes an infinite loop where it keeps passing data between each ModelFilter (unconfirmed). The error being returned is "PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted". 

I can use different key names (like a_active, b_active). I could also use the _other_ method for relationships but ideally I'd just like to pass 'active'. 

For example consider these ModelFilters which would be related to 2 Models both with a relationship with one another. 
```
class A extends ModelFilter
{
    public $relations = [
        'b' => ['active']
    ];

    public function active() {
        return $this->where('active', $value);
    }
}

class B extends ModelFilter
{
    public $relations = [
        'a' => ['active']
    ];

    public function active() {
        return $this->where('active', $value);
    }
}
```

Any ideas?

**Comment by GarethTIGFreight** [comment]
Okay I'm not sure if this a real issue but I think it won't matter to me anyhow as I'm using 1..* relationship between models and don't need to apply filters when there is only 1 anyway.

**Comment by Tucker-Eric** [comment]
Yes, there is actually a flag to disable relation filtering for this exact scenario. It's called when filtering a joined relation but not on regular relations. It should be updated for both. Good catch!

I will have an update for this soon.

**Comment by Tucker-Eric** [comment]
Actually, this is only when you're using the same key for related models which should not be done. There would be too many adverse effects if we disabled nesting relations beyond 1 child. The recommended workaround for this would be to use the `related()` method in the model filter like:
```php
class A extends ModelFilter
{
    public $relations = [];

    public function active()
    {
        $this->where('active', $value);
        $this->related('b', 'active', $value);
    }
}

class B extends ModelFilter
{
    public $relations = [];

    public function active()
    {
        $this->where('active', $value);
        $this->related('a', 'active', $value);
    }
}
```
Using the `related()` method is the suggested approach for relationships that are always filtered by another model filter. This allows you to not create a model filter for a model that you're never calling directly.

For example, if you have no need to call `B::filter($input)->get()` in your application then it's suggested you don't create a model filter for `B` and rely on the `related()` method of any filter that can be constrained with `B`.
