### ISSUE TITLE
Filters only effect initial query ... expected behaviour?

### ISSUE THREAD

**Issue by GarethTIGFreight** [Tucker-Eric/EloquentFilter#42]
Hello again, 

I've got (perhaps) an issue but I'm just hoping to conclude this is the expected behaviour or something is wrong / missing in my codebase. 

Consider this combination of ModelFilter _example_.
```
class ParentFilter extends ModelFilter
{
    public $relations = [
        'childModel' => ['active']
    ];
}

class ChildFilter extends ModelFilter
{
    public $relations = [];

    public function active($value) {
        return $this->where('active', $value);
    }
}
```
On the initial query it creates an "exist" sub-query and checks it can find atleast 1 child which is 'active'. 

```
select * from `parent_table`
where `uuid` = ?
and exists
    (select * from `children_table`
    where `parent_table`.`parent_id` = `children_table`.`parent_id`
    and `active` = ?
    and `children_table`.`deleted_at` is null)
and `parent_table`.`deleted_at` is null
```
```
(
    [0] => 3f151f53-935a-4577-af5b-ed6669524ad3
    [1] => 1
    [2] => 1
)
```

Then inevitably my code attempts to grab the children from the parent (e.g. ParentTable->childrenTable). And the code runs this query:
```
select * from `children_table`
where `children_table`.`parent_id` in (?)
and `children_table`.`deleted_at` is null
```
```
(
    [0] => 601
)
```
**Notice how the second query does not have an 'active' = 1 where clause.** 

Is this the expected behaviour or do I need to take an additional steps to ensure the ParentTable->childrenTable is properly filtered ( could this relate to the Model::with method? ). 

Thank you in advance and for also promptly answering my other issue yesterday.

**Comment by Tucker-Eric** [comment]
You are correct about the `with()` method not constraining the query the filter does. It won't apply the same constraints to the child because the query constraint is on the parent based on child models and doesn't necessarily mean the children need to be eager loaded.

You're going to have to apply the constraints to your `with()` method as well like:

```php
$input = ['active' => 1];

Parent::filter($input)
    ->with(['child' => function($query) use ($input) {
        return $query->filter($input);
    }])
    ->get();
```

**Comment by GarethTIGFreight** [comment]
Thanks for the prompt reply :)

Thanks, that's exactly what I needed. For anybody else's reference I'm also hoping to implement an additional child (e.g. Parent > Child > Grandchild). I'll likely try something like this:

```
$input = ['active' => 1];

Parent::filter($input)
    ->with(['child' => function($query) use ($input) {
        return $query->filter($input)->with(['grandChild' => function($query) use ($input) {
            return $query->filter($input);
        }]);
    }])
    ->get();
```

**Comment by GarethTIGFreight** [comment]
Adding to my previous reply we ended attaching a Eloquent\Scope to each Model. This will filter on **every** applicable Model (which is filterable). You'll likely want to check the route or some other paramater in the below code to only run those filters on certain routes.

```
<?php namespace OpenFreight\v3\Scopes;

use Illuminate\Database\Eloquent\Scope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class FilterScope implements Scope
{
    public function apply(Builder $builder, Model $model) {
        try {
            $builder->filter(app('request')->all());
        } catch (\BadMethodCallException $e) { // Is thrown when Model is not filterable}
    }
}
```

And this would be added on the applicable Models.
```
protected static function boot()
{
    parent::boot();
    static::addGlobalScope(new FilterScope);
}
```
