### ISSUE TITLE
Enhancement request - Low Priority:  Add model:filter custom stub path to config file

### ISSUE THREAD

**Issue by Alarich** [Tucker-Eric/EloquentFilter#45]
Greetings,

I'm an avid user of my own custom stubs and was wondering if perhaps it would be possible to get a config parameter that directs to a custom stub.

It's not that important though, I'll definitely manage without.

Sincerely,
Alarich

**Comment by Tucker-Eric** [comment]
Sounds simple enough. I'll add it to the next release and close this issue when it's merged.
