### ISSUE TITLE
Enhancement request / question: Eloquent orderBy option

### ISSUE THREAD

**Issue by hasentopf** [Tucker-Eric/EloquentFilter#51]
Hi Eric.
Thanks for this powerful Filter tool!
Is there a possibility to add an orderBy option to the filter?

Something like this:

_?title=lorem&sort:title&direction:asc_

Which automatically adds ->orderBy('title', 'asc') to the filter query.

Kind regards
Mathias

**Comment by hasentopf** [comment]
Thank you for the quick answer! Works great!
Next milestone: belongsToMany filtering 8-)

**Comment by Tucker-Eric** [comment]
BelongsToMany is already supported. Take a look at the `related()` method in the documentation.

**Comment by andrewstanton** [comment]
How would you be able to sort by related columns? Say I wanted to do api/rooms?sort_by=OH&sort_dir=DESC

Which has a Room hasOne Location
```
    public function location()
    {
        return $this->hasOne('App\Location', 'id', 'location_id');
    }
```

And that Location contains the state field. How would I be able to sort Rooms based on the Location state field?

Your help is appreciated!

**Comment by Tucker-Eric** [comment]
I'd add a join in the `sortBy` method and access the direction in there. Something along the lines of:

```php
public function sortBy($state)
{
    $this->join('locations', 'rooms.location_id', '=', 'locations.id')
        ->orderBy('locations.state', $this->input('sort_dir', 'ASC'));
}
```

**Comment by andrewstanton** [comment]
Good suggestion thank you!
