### ISSUE TITLE
Filter whereBetween

### ISSUE THREAD

**Issue by masterpieceicang** [Tucker-Eric/EloquentFilter#52]
How do i make whereBetween($par1, $par2) ? in my ModelFilter

**Comment by masterpieceicang** [comment]
Its fixed, i make an array();

**Comment by Tucker-Eric** [comment]
You can also access any input with `$this->input('key')`.

When I do a start/end parameter I use 2 parameters in my url and in one of the filter methods, access the other data. 

So url like: `/my-url?start_date=2018-01-01&end_date=2018-03-01`

In the controller:
```php
public function index(Request $request)
{
    return MyModel::filter($request->all())->get();
}
```

In the model's filter:
```php
public function startDate($date)
{
    return $this->whereBetween('date_col', [$date, $this->input('end_date')]);
}
```
