### ISSUE TITLE
Using OR relation

### ISSUE THREAD

**Issue by liran-co** [Tucker-Eric/EloquentFilter#59]
I read the previous issues regarding using an OR relation - I've been able to make this work. The issue I've run into is applying the orWhere() only after the first filter. I'm including an attribute in the request to indicate whether or not the user would like all the filters to apply as OR or AND. However in order to make this work, the first filter needs to be a where() and the subsequent ones should use orWhere().

**Comment by Tucker-Eric** [comment]
You can actually include this in the `where()` conditions inside the methods that use that user supplied value to differ between OR and AND where the last parameter of [`where()`](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Eloquent/Builder.php#L219) is `or` or `and`.

You'd be able to grab that user supplied and/or descriptor via the filter's `input()` method and supply a default in case one wasn't supplied.

The first `where()` doesn't need to be executed before an `orWhere` can be used as `orWhere()` is just `where($column, $operater, $value, 'or')`

All together that would look like:

```php
public function myFilterMethod($val)
{
    return $this->where('my_filter_val', '=', $val, $this->input('and_or_flag', 'and'));
}
```

**Comment by liran-co** [comment]
This doesn't seem to work - it provides results outside the filter. If or is applied to the first filter, it just returns the entire data set. 

`?chain=or&firstName[0]=is&firstName[1]=tal`

```
protected $chainer = null;
    
public function setup()
{
    $this->chainer = $this->input('chain', 'and');
}

public function stringFilter($filter, $attribute) {
	    
    $comparer = $filter[0];
    $value = $filter[1];
	    
    switch ($comparer) {
        case "is":
            return $this->where($attribute, '=', $value, $this->chainer);
        case "begins":
            return $this->where($attribute, 'LIKE', $value.'%', $this->chainer);
        case "ends":
            return $this->where($attribute, 'LIKE', '%'.$value, $this->chainer);
        case "contains":
            return $this->where($attribute, 'LIKE', '%'.$value.'%', $this->chainer);
    }
	    
}

public function firstName($first) 
{
    return $this->stringFilter($first, 'first_name');
}

```

**Comment by Tucker-Eric** [comment]
What is the sql output from your query builder after calling filter?

You can dump it in your controller with something like:

```php
public function index(Request $request)
{
    dd(MyModel::filter($request->all())->toSql());
}
```

**Comment by Tucker-Eric** [comment]
Ahhh, I see what's going on here. For the future I think adding named nested `where` statements to the filter would be a great way to solve this issue and many other similar ones that would arise from using an `orWhere` after a relation.

For now, since you said the condition is working if the first filter is a `where` I think you'd be able to solve this by adding to your `setup` method:

```php
public function setup()
{
    $this->chainer = $this->input('chain', 'and');
    $this->where(1, '=', 1);
}
```
This way you'll always be chaining off of a `where`.

**Comment by liran-co** [comment]
This wouldn't work either since it results in ```and (1 = 1 or `first_name` = ?)``` which still returns all results.

**Comment by Tucker-Eric** [comment]
Hmmm, what about nesting the filter after the relation like:

```php
$account->transactions()->where(function($q) use ($request) {
    return $q->filter($request->all());
})->get();
```

**Comment by liran-co** [comment]
Success!
