### ISSUE TITLE
How do I query date between since there are only three eloquent methods to be used?

### ISSUE THREAD

**Issue by emanueluser** [Tucker-Eric/EloquentFilter#62]

**Comment by wangchengtao** [comment]
Hi guys，has the problem been solved? Could you tell me how to solve it.

**Comment by emanuellimabr** [comment]
@wangchengtao I solved it creating two methos, the first one is used to filter the start date if there is no end date, or if it is, it filters the result between them.
 
`public function dataEnvioInicio($date)
    {
        $sdate = data_banco($date);
        $edate = \Carbon\Carbon::parse(data_banco($this->input('data_envio_fim')))->addDays(1)->format('Y-m-d');

        if (empty($this->input('data_envio_fim'))) {
            return $this->where('data_envio', '>=', $sdate);
        } else {
            return $this->whereBetween('data_envio', [$sdate, $edate]);
        }
    }

    public function dataEnvioFim($date)
    {
        $sdate = \Carbon\Carbon::parse(data_banco($this->input('data_envio_inicio')))->format('Y-m-d');
        $edate = \Carbon\Carbon::parse(data_banco($date))->addDays(1)->format('Y-m-d');

        if (empty($this->input('data_envio_inicio'))) {
            return $this->where('data_envio', '<=', $edate);
        } else {
            return $this->whereBetween('data_envio', [$sdate, $edate]);
        }
    }`

**Comment by Tucker-Eric** [comment]
Yup! You're going to want to use `$this->input(URL_PARAM)` to get the value of the upper/lower end of the constraint if you're set on using `whereBetween` if not then 2 methods work just fine, one for the upper bound and one for the lower bound that way it's just a greater than/less than query if only one of the input parameters is missing.

**Comment by wangchengtao** [comment]
@emanuellimabr @Tucker-Eric Thanks! I resolved it.
