### ISSUE TITLE
Is there a new feature? Document has not been updated in two years

### ISSUE THREAD

**Issue by iiDestiny** [Tucker-Eric/EloquentFilter#63]

**Comment by robclancy** [comment]
I saw a joins variable with no documentation on joins.

Also I'd like to extend but you use snake case. 

The stub is also based on old Laravel 4 syntax styles.

I'd like to use this package but I feel like I'd rather just fork it privately and keep in sync with upstream, are there are future plans? Changes I'd like to make you might not agree with so the PR route might not work?

**Comment by Tucker-Eric** [comment]
[Blacklist](https://github.com/Tucker-Eric/EloquentFilter#blacklist) feature just added and documented

**Comment by hk1165411366** [comment]
i don`t know how to use

**Comment by Tucker-Eric** [comment]
Just tagged [Release 1.4.0](https://github.com/Tucker-Eric/EloquentFilter/releases/tag/1.4.0). This adds option to toggle camel case method naming strategy via `protected $camel_cased_methods` property and `convertToCamelCasedMethods` method.
