### ISSUE TITLE
Arrays as multiple filters

### ISSUE THREAD

**Issue by liran-co** [Tucker-Eric/EloquentFilter#64]
It seems that utilizing arrays does not account for the case that you may want to apply the same filter multiple times. Instead of calling the filter once with an array as the input, how can we achieve calling the filter multiple times with each input being one item in the array?

**Comment by imoveis** [comment]
Is it possible to do with related table?


i use 

public function neighborhood($value){
        return $this->related('location', 'neighborhood_slug', '=', $value);
}


I tested the examples above, they didn't work.

**Comment by Tucker-Eric** [comment]
Ya you can, you just want to pass a closure to `related` instead. So something like: 

```php
public function neighborhood($arrayValue)
{
    return $this->related('location', function($query) use ($arrayValue) {
        foreach($arrayValue as $key => $value) {
            $query->orWhere('neighborhood_slug', $value);
        }
    });
}
```

**Comment by imoveis** [comment]
> ```
> public function neighborhood($arrayValue)
> {
>     return $this->related('location', function($query) use ($arrayValue) {
>         foreach($arrayValue as $key => $value) {
>             $query->orWhere('neighborhood_slug', $value);
>         }
>     });
> }
> ```

dont work.



Query String: ?neighborhood[]=canhema&neighborhood[]=centro


controller 

return Model::filter($request->all())->get();





function in filter file
public function neighborhood($arrayValue)
{
    return $this->related('location', function($query) use ($arrayValue) {
        foreach($arrayValue as $key => $value) {
            $query->orWhere('neighborhood_slug', $value);
        }
    });
}


:/

**Comment by imoveis** [comment]
I used this example based on the documentation / main page and it worked!

Thank you.

`public function neighborhood($array)
    {
        return $this->whereHas('location', function($query) use ($array)
        {
            return $query->whereIn('neighborhood_slug', $array);
        });
    `}``
