### ISSUE TITLE
[ASK] problem with column prefix

### ISSUE THREAD

**Issue by cacing69** [Tucker-Eric/EloquentFilter#68]
i have success use this lib with normal table, 

so i have table, with prefix column, how to define primary column or how to change default sort column

![screenshot_209](https://user-images.githubusercontent.com/36250619/40852013-488617a4-65f3-11e8-9f35-2876f8f14098.png)

this is my table
![screenshot_210](https://user-images.githubusercontent.com/36250619/40852030-56a5aa7a-65f3-11e8-8e8a-4136b33e3bc1.png)

**Comment by Tucker-Eric** [comment]
See [Defining Models](https://laravel.com/docs/master/eloquent#defining-models).

On your model add:
```php
protected $primaryKey = 'memeq_id';
```

**Comment by cacing69** [comment]
i'm already define my primary key on my model

sorry for my bad english
![screenshot_211](https://user-images.githubusercontent.com/36250619/40856668-df93e9fa-6602-11e8-87c3-4e05339db898.png)

**Comment by cacing69** [comment]
no, i didnt use any method on my filter, wait a minute, i will send my controller and my modelFilter here

**Comment by cacing69** [comment]
sorry this is my bad, when i create some helper and set default order to id

![screenshot_213](https://user-images.githubusercontent.com/36250619/40857423-51c1a9b6-6605-11e8-95b3-dd859e16a260.png)
