### ISSUE TITLE
1.3.2 update breaks

### ISSUE THREAD

**Issue by alexnoise79** [Tucker-Eric/EloquentFilter#73]
HI,

I updated to version 1.3.2 and i have this error:

> FatalErrorException in ModelFilter.php line 571:
Call to undefined method Illuminate\Database\Eloquent\Relations\Relation::hasMacro()
in ModelFilter.php line 571

at Application->handleShutdown() in RegistersExceptionHandlers.php line 55
at Application->Laravel\Lumen\Concerns\{closure}()

forcing the version to 1.3.1 in composer.json solve the error.

**Comment by Tucker-Eric** [comment]
Ahh, thanks for opening the issue! Will resolve and get a patch out asap.

**Comment by alexnoise79** [comment]
You're welcome, btw your plugin is amazing :)

**Comment by Tucker-Eric** [comment]
Thanks!

We should be good to go with [1.3.3](https://github.com/Tucker-Eric/EloquentFilter/releases/tag/1.3.3) for that BC break.
