### ISSUE TITLE
Filtering By Relationships: based on their average value

### ISSUE THREAD

**Issue by ahkmunna** [Tucker-Eric/EloquentFilter#76]
I need to filter items base on rating score. Like, pick all items that have average ratings > 4. Is it possible? I didn't find anything on the document.

**Comment by Tucker-Eric** [comment]
If you want to be able to control the operand (`>`,`=`,`<`) you can do something similar to #58 and #52 where you can pass that operand as the first character of the value and handle the logic in your filter method:

```php
public function rating($rating)
{
    $operands = ['>', '=', '<'];

    if(is_string($rating) && in_array($rating[0], $operands)) {
        return $this->where('rating', $rating[0], substr($rating, 1))
    }

    return $this->where('rating', '>', $rating);
}
```

Or if you are always going to do a greater than operand you would just use that in your filter method for that key:

```php
public function rating($rating)
{
    return $this->where('rating', '>', $rating);
}
```

**Comment by ahkmunna** [comment]
Thanks for your reply! I only need avg of relation and only greater than. But This gives me SQL error::

`SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'project_db.ratings.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by ....`

**Comment by Tucker-Eric** [comment]
You can update your query to:

```php
public function rating($rating)
{
    return $this->related('rating', function($query) use ($rating) {
        return $query->select(DB::raw('AVG(score) as avg_score'))
            ->having('avg_score', '>', $rating);
    });
}
```
Or just disable strict mode per [this write up](https://mattstauffer.com/blog/strict-mode-and-other-mysql-customizations-in-laravel-5-2/), you can update that setting in your `config/database.php`:

```php
'connections' => [
        'mysql' => [
            // Behave like MySQL 5.6
            'strict' => false,

            // Behave like MySQL 5.7
            'strict' => true,
        ]
    ]
```

```php

    'connections' => [
        'mysql' => [
            // Ignore this key and rely on the strict key
            'modes' => null,

            // Explicitly disable all modes, overriding strict setting
            'modes' => [],

            // Explicitly enable specific modes, overriding strict setting
            'modes' => [
                'STRICT_TRANS_TABLES',
                'ONLY_FULL_GROUP_BY',
            ],
        ]
    ]
```

**Comment by ahkmunna** [comment]
Working after disabling the strict mode. thanks
