### ISSUE TITLE
Relationship ID based filtering

### ISSUE THREAD

**Issue by andrewstanton** [Tucker-Eric/EloquentFilter#77]
First off, this package is amazing, appreciate all the hardwork! Really is helping me out.

I'm trying to using filtering on top of api endpoints for specific models. For example I would call this endpoint:
_/api/instructor/10/classes_

That endpoint would pull only the classes associated with that instructor, but I want to be able to add filter such as:
_/api/instructor/10/classes?start=2018-08-15&end=2018-08-17_

My code currently for the api endpoint controller looks like this:
```
public function index($id)
{
        $instructor = Instructor::findOrFail($id);
        $classes = $instructor->classes();

        return (new InstructorClassesResource($classes))->response()->setStatusCode(200);
 }
```
But wondering how would I implement the filter on top of the **findOrFail** by id? Would I have to pass a parameter to the setup function?

Would appreciate guidance! Thank you

**Comment by Tucker-Eric** [comment]
Hey! Thanks for the kind words!!

`findOrFail` isn't a static method so it can be added to the end. It technically adds a `where('id', '=', $id)` to the query and then executes it so it's just adding another constraint after the filter below.

As long as your `Instructor` model implements the `Filterable` trait and you've created a filter for your `Instructor` model you should be fine doing:

```php
public function index($id)
{
    $instructor = Instructor::filter(request()->all())->findOrFail($id);
    $classes = $instructor->classes();

    return (new InstructorClassesResource($classes))->response()->setStatusCode(200);
}
```

If you need to filter your classes by date then you'd create your `Class` model filter and do:
```php
public function index($id)
{
    $instructor = Instructor::findOrFail($id);
    // Calling classes() here returns a query on the Classes model so filter() here uses the classes model filter
    $classes = $instructor->classes()->filter(request()->all());

    return (new InstructorClassesResource($classes))->response()->setStatusCode(200);
}
```

**Comment by andrewstanton** [comment]
Oh I gotcha that makes sense now! Appreciate the help
