### ISSUE TITLE
Filter out [ 0 => null ] parameters by default

### ISSUE THREAD

**Issue by chanjsq** [Tucker-Eric/EloquentFilter#79]
When send request using `types[]=`, the received input is:

```php
[
    0 => null,
]
```

Which will go into the filter methods.

This is not wanted.

**Comment by Tucker-Eric** [comment]
Technically that is the desired behavior and the check should lie in the filter method for that input or you can remove it in the `setup` method of the filter. #58 gives some insight as to why I wouldn't want to check or exclude values based on the content of an array.

If you want to not forward that to the filter method that handles that input you can add an input filter to your setup method:

```php
public function setup()
{
    $this->input = array_filter($this->input, function($val) {
        return !(is_array($val) && count($val) === 1 && $val[0] === null);
    });
}
```

**Comment by chanjsq** [comment]
@Tucker-Eric Thanks for the reply. 💯
