### ISSUE TITLE
Relation query with a same field name cause errors.

### ISSUE THREAD

**Issue by chanjsq** [Tucker-Eric/EloquentFilter#80]

**Comment by chanjsq** [comment]
Works:

```php
public function hospital($id)
{
    $this->related('hospitals', 'tb_hospital.id', $id);
}
```

Doesn't work:

```php
public function hospital($id)
{
    $this->related('hospitals', 'id', $id);
}
```

**Comment by Tucker-Eric** [comment]
What's the error you get?

**Comment by chanjsq** [comment]
The error message is: `Column 'id' in where clause is ambiguous`.

Generated SQL is:

```sql
SELECT count(*) AS AGGREGATE 
  FROM `tb_customer`
  WHERE EXISTS (
    SELECT * FROM `tb_hospital`
      INNER JOIN `tb_record`
        ON `tb_hospital`.`id` = `tb_record`.`hospital_id`
      WHERE `tb_customer`.`id` = `tb_record`.`customer_id`
        AND `id` = 2
  )
```

While the correct SQL should be:

```sql
SELECT count(*) AS AGGREGATE 
  FROM `tb_customer`
  WHERE EXISTS (
    SELECT * FROM `tb_hospital`
      INNER JOIN `tb_record`
        ON `tb_hospital`.`id` = `tb_record`.`hospital_id`
      WHERE `tb_customer`.`id` = `tb_record`.`customer_id`
        AND `tb_hospital`.`id` = 2
  )
```

Notice the difference is the generated SQL missed table name part `tb_hospital`.

The example relations of `Customer` and `Hospital` is `many to many` relationship.

**Comment by Tucker-Eric** [comment]
This isn't in the `relation` method. The `relation` method just [adds a where clause](https://github.com/Tucker-Eric/EloquentFilter/blob/master/src/ModelFilter.php#L180) so you would be running into this error building your query without a model filter and would still need to constrain your query by `tb_hospital.id`.

**Comment by Tucker-Eric** [comment]
You could use the `getRelatedTable` method in the model filter like:

```php
public function hospital($id)
{
    $this->related('hospitals', $this->getRelatedTable('hospitals') . '.id', $id);
}
```

**Comment by chanjsq** [comment]
@Tucker-Eric Wow! Great idea! Thanks! 👍
