### ISSUE TITLE
Undefined function camel_case() in 1.4.0 version

### ISSUE THREAD

**Issue by ITKain** [Tucker-Eric/EloquentFilter#87]
If the project uses a separate Eloquent ORM, instead of a full-fledged Laravel, then an error occurs: 
`Call to undefined function EloquentFilter\\camel_case()`

It would be better not to depend on Laravel helpers.

**Comment by Tucker-Eric** [comment]
Ahh, we do require `illuminate/support` so we can swap out `camel_case` with `Illuminate\Support\Str::camel` here https://github.com/Tucker-Eric/EloquentFilter/blob/master/src/ModelFilter.php#L202 if you wanted to send a pr for it?
