### ISSUE TITLE
Filtering on absence of a relationship

### ISSUE THREAD

**Issue by sburkett** [Tucker-Eric/EloquentFilter#89]
I have a rather large need to filter on the absence of a relationship. Unfortunately, I can't just do:

```php
public function myFilter($status)
{
    return $this->related('listings', 'type', '!=', $status);
}
```
... as this will simply return records with other values, instead of returning records where there is no relationship.

This is basically what I want to do, but this won't work as `whereDoesntHave` is a method of `Eloquent\Builder`, and not `Eloquence\Builder`:

```
  public function myFilter($status)
  {
    return $this->whereDoesntHave('listings', function (Builder $query) use ($status) {
         $query->where('type', $status);
     });
  }
```

Any ideas? Thanks in advance!

**Comment by sburkett** [comment]
Well, I think I figured it out lol. I needed to remove the `Builder` from the argument list of the closure in the `whereDoesntHave`. I *think* it works, but will need to verify the data. So what I have now is:

```php
 public function myFilter($status)
  {
    return $this->whereDoesntHave('listings', function ($query) use ($status) {
         $query->where('type', $status);
     });
  }
```

**Comment by Tucker-Eric** [comment]
Hey @sburkett, just to clarify, are you looking to constrain your query by the absence of the `listings` relation? Or are you looking to constrain the query by the `type` column on your `listings` relation?

If you are looking to get everything that doesn't have `listings` it would be:
```php
public function myFilter()
{
    return $this->whereDoesntHave('listings');
}
```

If you are looking to only return records where the listing's `type` column is not a status then your first example was correct
```php
public function myFilter($status)
{
    return $this->related('listings', 'type', '!=', $status);
}
```

The `related` method stores all calls to that relation and groups them all in a single `whereHas` scope for that relation. So the above example is equivalent to:

```php
public function myFilter($status)
{
    return $this->whereHas('listings', function($query) use ($status) {
         return $query->where('type', '!=', $status);
    });
}
```

You may be getting other results if you have other calls to `$this->related('listings')` elsewhere.

**Comment by sburkett** [comment]
Hi Eric, and thanks for the response! Your second example, I believe, is correct for my situation. I am constraining on the absence of a `Listing`  relation of a given type.  This is a filter for a `Sku` model. And a `Sku` can have multiple `Listing` records, but only one `Listing` record of a given `type`.

However, those two queries don't produce the exact same result set. Using my condition check in the `whereDoesntHave` results in this query:

```
select
  count(*) as aggregate
from
  `skus`
where
  not exists (
    select
      *
    from
      `listings`
    where
      `skus`.`id` = `listings`.`sku_id`
      and `type` = "EbayListing"
  )
  and `item_id` is not null
```

and yours one-liner turns into:

```
select
  count(*) as aggregate
from
  `skus`
where
  exists (
    select
      *
    from
      `listings`
    where
      `skus`.`id` = `listings`.`sku_id`
      and `type` != "EbayListing"
  )
  and `item_id` is not null
```

The `whereDoesntHave` seems to be the correct one in this particular scenario, as it checks for the non-existence of a result. Performance is a bit of an issue right now with the query, though, so I may need to look at the indexes, or perhaps take a slightly different approach to it.

BTW, thanks for a terrific package. I wasn't even aware of your package until I inherited this project that utilized it. It is quite the little timesaver!

I'm working on a few little projects as well. The first one is available now if you wanna check it out:

https://github.com/sburkett/laravel-s3-tools

And I'm also working on a Laravel package to interface with the VICI protocol used by certain VPN platforms (notably Strongswan). Handy for things like bringing a VPN connection up/down in Laravel jobs that need to transmit data over a VPN, but not leave the VPN connection lingering.

**Comment by Tucker-Eric** [comment]
Ahhh, that makes sense. Because if a `Sku` has many `Listing`s and one of them isn't of the type to exclude the condition passes even if it has that type because there are some without. 

Yup, 2nd part works. 

Your S3 package looks great and will definitely use it when the need arises!
 
Cheers!
