### ISSUE TITLE
Method isReadable does not exist when `php artisan model:filter <Model>

### ISSUE THREAD

**Issue by zr87** [Tucker-Eric/EloquentFilter#96]
package version: v1.4.2
Laravel v5.2.45

Error running  when `php artisan model:filter Product`:
   ```                              
  [BadMethodCallException]           
  Method isReadable does not exist.  
```

**Comment by Tucker-Eric** [comment]
Yup. Looks like it was added in [5.3.7](https://github.com/laravel/framework/commit/4c0c08c5aef8618f81cbcb508873ce3a4e2e7d15)

Just published [1.4.3](https://github.com/Tucker-Eric/EloquentFilter/releases/tag/1.4.3) which should have the fix.

Cheers!
